### ISSUE TITLE
[Suggestion] There should be a setup instruction

### ISSUE THREAD

**Issue by longnd** [thiennc1107/search-analyzer#2]
## Issue
Given that not everybody will be familiar with the technical stack chosen for any given project, it is always recommended to have a setup instruction to document the process to set up and run the application on a development (and other) environment(s).  
This application provides makefile with various commands + docker-compose file so that some simple guidelines would be much more helpful.

I managed to set up and run the application on my local, so fixing this issue is unnecessary. This is just a suggestion :)

**Comment by thiennc1107** [comment]
Hi, I already added a setup section in this PR, can you please help to review:
https://github.com/thiennc1107/search-analyzer/pull/5/files
Thanks for your suggestion.
