### ISSUE TITLE
Lack of Git flow

### ISSUE THREAD

**Issue by longnd** [thiennc1107/search-analyzer#3]
## Issue
Even though you worked solo in this project, it was a clear requirement for this code challenge that:
> Use Git during the development process. Push to a public repository on Github or Gitlab.  Make regular commits and **merge code using pull requests.**

We expect the changes to be merged by using pull requests; the reason is it helps show your planning skills, i.e. how you analyze the given requirements, break it down into smaller achievable parts, and implement them in each pull request. Also, by going through the PRs, we can evaluate if you know to use Git flow efficiently (which is crucial when working in a development team)

**Comment by thiennc1107** [comment]
Thanks for your suggestion, I will notice this in up-coming changes.
